# Generated by Django 6.0 on 2025-12-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='day_pt_discharged',
            field=models.DateField(blank=True, null=True),
        ),
    ]
